### ISSUE TITLE
[Suggestion-Kantele] Hide active player in look view

### ISSUE THREAD

**Issue by nemmons** [oestrich/kalevala#5]
As a player, when i type the 'look' command, i wouldn't expect to see my own character name in the room description

**Comment by nemmons** [comment]
I did a naive implementation of this (which, to clarify, i haven't pushed anywhere yet) by rejecting the current character from the list of characters via pid comparison (using event.from_pid). @oestrich mentioned that we should do something better than comparing pids so i have refactoring in mind to inject the character's actual id into the event ( event.from_character_id or perhaps event.acting_character_id ??)

**Comment by oestrich** [comment]
Fixed in 9a5b15fa7a3c2b29d8ffa81fc33548815dc64fc5

Thanks for reporting!
