### ISSUE TITLE
Bug - Kalevala.World.Room.Movement handle_request 'abort' case has wrong signature

### ISSUE THREAD

**Issue by nemmons** [oestrich/kalevala#7]
Sorry if i'm misunderstanding something, but i think the pattern matching is incorrect in the signature of [Kalevala.World.Room.Movement.handle_request](https://github.com/oestrich/kalevala/blob/master/lib/kalevala/world/room.ex#L82) because aborted should be an element of the event's 'data' element, not of the event itself (for reference, the event is created [here](https://github.com/oestrich/kalevala/blob/master/example/lib/kantele/world/room.ex#L46)).

It looks like this was missed when similar function signatures were upgraded in 95fc0246626cbbcd423edcdbebc4dbddaa7eab49 (e.g. [here](https://github.com/oestrich/kalevala/commit/95fc0246626cbbcd423edcdbebc4dbddaa7eab49#diff-95abbdceb2f739edbeb931f53649792dR96) )

I believe the signature should be `def handle_request(movement_voting = %Event{topic: Voting, data: %{aborted: true}}, _state) do` - if you agree i'm happy to provide a PR

**Comment by oestrich** [comment]
I believe you are correct. A PR would be great! 😄

**Comment by oestrich** [comment]
Fixed in master (2e2014b07cbafd366505c6a0fed66653c400f1ae)
